spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: banking_user
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

logging:
  level:
    root: WARN
    com:
      example: INFO
